defaults: &defaults
  adapter: mysql
  encoding: utf8
  username: root
  password: db4root
  socket: /var/run/mysqld/mysqld.sock

development:
  database: lasbuenasnoches
  <<: *defaults

production:
  database: lasbuenasnoches
  <<: *defaults


test:
  adapter: sqlite3
  database: db/test.sqlite3
  timeout: 5000
